services:
  - type: web
    name: telegram-voice-bot
    runtime: python
    repo: https://github.com/dmkarbushev/telegram-voice-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11.0
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
